// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-SxMarS3DTDBXc5eknevQ53H83PEygd0',
    appId: '1:950037215961:web:c811f6721c0afa7a4adcc8',
    messagingSenderId: '950037215961',
    projectId: 'gas-7f0d1',
    authDomain: 'gas-7f0d1.firebaseapp.com',
    storageBucket: 'gas-7f0d1.firebasestorage.app',
    measurementId: 'G-7HRJ9N09M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWu-PhMq1M03LaFJ2u-KPgiCWjyQ3BDQ',
    appId: '1:950037215961:android:395e51cab62dbf114adcc8',
    messagingSenderId: '950037215961',
    projectId: 'gas-7f0d1',
    storageBucket: 'gas-7f0d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs_LZYefP5f-EYvDHIeti1Cg1RozM7S-8',
    appId: '1:950037215961:ios:bdde81145bff66e34adcc8',
    messagingSenderId: '950037215961',
    projectId: 'gas-7f0d1',
    storageBucket: 'gas-7f0d1.firebasestorage.app',
    iosBundleId: 'com.yodev.twogas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs_LZYefP5f-EYvDHIeti1Cg1RozM7S-8',
    appId: '1:950037215961:ios:b324b2ae0be3bcd94adcc8',
    messagingSenderId: '950037215961',
    projectId: 'gas-7f0d1',
    storageBucket: 'gas-7f0d1.firebasestorage.app',
    iosBundleId: 'com.yodev.twogas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-SxMarS3DTDBXc5eknevQ53H83PEygd0',
    appId: '1:950037215961:web:511e990c7e253bda4adcc8',
    messagingSenderId: '950037215961',
    projectId: 'gas-7f0d1',
    authDomain: 'gas-7f0d1.firebaseapp.com',
    storageBucket: 'gas-7f0d1.firebasestorage.app',
    measurementId: 'G-6ZHZ62RTBS',
  );
}
